numerical_columns:
  - Seniority
  - Policies_in_force
  - Max_policies
  - Max_products
  - Lapse
  - Payment
  - N_claims_year
  - N_claims_history
  - Type_risk
  - Area
  - Second_driver
  - Year_matriculation
  - Power
  - Cylinder_capacity
  - N_doors
  - Weight

float_columns:
  - Premium
  - Cost_claims_year
  - R_Claims_history
  - Value_vehicle
  - Length

categorical_columns:
  - Date_driving_licence
  - Distribution_channel
  - Type_fuel

columns:
  - ID
  - Date_start_contract
  - Date_last_renewal
  - Date_next_renewal
  - Date_birth
  - Date_driving_licence
  - Distribution_channel
  - Seniority
  - Policies_in_force
  - Max_policies
  - Max_products
  - Lapse
  - Date_lapse
  - Payment
  - Premium
  - Cost_claims_year
  - N_claims_year
  - N_claims_history
  - R_Claims_history
  - Type_risk
  - Area
  - Second_driver
  - Year_matriculation
  - Power
  - Cylinder_capacity
  - Value_vehicle
  - N_doors
  - Type_fuel
  - Length
  - Weight

power_transformed_features:
  - Seniority
  - Policies_in_force
  - Max_policies
  - Max_products
  - Lapse
  - Payment
  - Premium
  - N_claims_year
  - N_claims_history
  - Area
  - Second_driver
  - Value_vehicle
  - Length
  - Weight

drop_columns:
  - ID